import type { Destination, TourPackage, Testimonial, GalleryImage, Stat } from "@/types";

export const destinations: Destination[] = [
  {
    id: "1",
    name: "Santorini",
    country: "Greece",
    continent: "Europe",
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80",
    rating: 4.9,
    reviews: 2847,
    price: 1299,
    duration: "7 days",
    category: ["Beach", "Romance", "Culture"],
    description: "Iconic white-washed buildings perched on volcanic cliffs above the stunning Aegean Sea.",
    highlights: ["Oia Sunset", "Caldera Views", "Wine Tasting", "Ancient Akrotiri"],
    featured: true,
  },
  {
    id: "2",
    name: "Bali",
    country: "Indonesia",
    continent: "Asia",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
    rating: 4.8,
    reviews: 3921,
    price: 899,
    duration: "10 days",
    category: ["Culture", "Adventure", "Spiritual"],
    description: "The Island of Gods — lush rice terraces, ancient temples, and vibrant spiritual culture.",
    highlights: ["Ubud Monkey Forest", "Tanah Lot", "Rice Terraces", "Kuta Beach"],
    featured: true,
  },
  {
    id: "3",
    name: "Machu Picchu",
    country: "Peru",
    continent: "South America",
    image: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800&q=80",
    rating: 4.9,
    reviews: 1654,
    price: 1599,
    duration: "8 days",
    category: ["Adventure", "History", "Trekking"],
    description: "The Lost City of the Incas — a mystical ancient citadel high in the Andes Mountains.",
    highlights: ["Inca Trail", "Sun Gate", "Huayna Picchu", "Sacred Valley"],
    featured: true,
  },
  {
    id: "4",
    name: "Maldives",
    country: "Maldives",
    continent: "Asia",
    image: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800&q=80",
    rating: 5.0,
    reviews: 1243,
    price: 2499,
    duration: "7 days",
    category: ["Beach", "Luxury", "Romance"],
    description: "Crystal-clear turquoise lagoons, overwater bungalows, and pristine coral reefs.",
    highlights: ["Overwater Villas", "Snorkeling", "Whale Sharks", "Sunset Cruises"],
    featured: true,
  },
  {
    id: "5",
    name: "Kyoto",
    country: "Japan",
    continent: "Asia",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80",
    rating: 4.8,
    reviews: 2109,
    price: 1199,
    duration: "9 days",
    category: ["Culture", "History", "Food"],
    description: "Japan's ancient capital with thousands of classical Buddhist temples and traditional geisha districts.",
    highlights: ["Fushimi Inari", "Arashiyama", "Geisha District", "Tea Ceremony"],
    featured: true,
  },
  {
    id: "6",
    name: "Safari Kenya",
    country: "Kenya",
    continent: "Africa",
    image: "https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&q=80",
    rating: 4.9,
    reviews: 987,
    price: 3299,
    duration: "12 days",
    category: ["Wildlife", "Adventure", "Nature"],
    description: "Witness the Great Migration across the Masai Mara — the greatest wildlife show on Earth.",
    highlights: ["Big Five", "Great Migration", "Masai Village", "Hot Air Balloon"],
    featured: true,
  },
  {
    id: "7",
    name: "Amalfi Coast",
    country: "Italy",
    continent: "Europe",
    image: "https://images.unsplash.com/photo-1534445538923-ab38e2aff7cf?w=800&q=80",
    rating: 4.7,
    reviews: 1876,
    price: 1799,
    duration: "8 days",
    category: ["Beach", "Culture", "Food"],
    description: "Dramatic cliffs, colorful villages, and Mediterranean cuisine along Italy's most beautiful coastline.",
    highlights: ["Positano", "Ravello", "Boat Tours", "Limoncello Tasting"],
    featured: false,
  },
  {
    id: "8",
    name: "Patagonia",
    country: "Argentina/Chile",
    continent: "South America",
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
    rating: 4.9,
    reviews: 743,
    price: 2899,
    duration: "14 days",
    category: ["Adventure", "Nature", "Trekking"],
    description: "The end of the world — dramatic glaciers, jagged peaks, and untamed wilderness.",
    highlights: ["Torres del Paine", "Perito Moreno", "W Trek", "Los Glaciares"],
    featured: false,
  },
];

export const tourPackages: TourPackage[] = [
  {
    id: "1",
    title: "Greek Islands Odyssey",
    destination: "Greece",
    image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=800&q=80",
    images: [],
    price: 2499,
    originalPrice: 3199,
    duration: "14 days",
    groupSize: "8-12",
    difficulty: "Easy",
    rating: 4.9,
    reviews: 324,
    includes: ["Flights", "Hotels", "Breakfast", "Guided Tours", "Ferry Tickets"],
    itinerary: [
      { day: 1, title: "Arrive in Athens", description: "Welcome dinner at Plaka", activities: ["Airport pickup", "Hotel check-in", "Welcome dinner"] },
      { day: 2, title: "Athens Highlights", description: "Acropolis and Parthenon tour", activities: ["Acropolis Museum", "Parthenon", "Greek lunch"] },
    ],
    category: "Beach & Culture",
    badge: "Best Seller",
    departure: "Every Saturday",
  },
  {
    id: "2",
    title: "Bali Spirit Journey",
    destination: "Bali, Indonesia",
    image: "https://images.unsplash.com/photo-1604999565976-8913ad2ddb37?w=800&q=80",
    images: [],
    price: 1499,
    originalPrice: 1999,
    duration: "10 days",
    groupSize: "6-10",
    difficulty: "Easy",
    rating: 4.8,
    reviews: 512,
    includes: ["Villa Stay", "Daily Breakfast", "Yoga Classes", "Temple Tours", "Cooking Class"],
    itinerary: [],
    category: "Cultural & Spiritual",
    badge: "Most Popular",
    departure: "Every Monday",
  },
  {
    id: "3",
    title: "Inca Trail Adventure",
    destination: "Peru",
    image: "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&q=80",
    images: [],
    price: 2199,
    originalPrice: 2699,
    duration: "8 days",
    groupSize: "4-8",
    difficulty: "Challenging",
    rating: 4.9,
    reviews: 198,
    includes: ["Camping Gear", "All Meals", "Expert Guide", "Train Tickets", "Entry Permits"],
    itinerary: [],
    category: "Adventure",
    badge: "Challenging",
    departure: "Every Thursday",
  },
  {
    id: "4",
    title: "Maldives Luxury Escape",
    destination: "Maldives",
    image: "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80",
    images: [],
    price: 4999,
    originalPrice: 6499,
    duration: "7 days",
    groupSize: "2-4",
    difficulty: "Easy",
    rating: 5.0,
    reviews: 87,
    includes: ["Overwater Villa", "Full Board", "Snorkeling", "Seaplane Transfer", "Spa Credit"],
    itinerary: [],
    category: "Luxury",
    badge: "Luxury",
    departure: "Any day",
  },
  {
    id: "5",
    title: "Japan Cultural Immersion",
    destination: "Japan",
    image: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80",
    images: [],
    price: 3299,
    originalPrice: 3999,
    duration: "12 days",
    groupSize: "6-12",
    difficulty: "Easy",
    rating: 4.8,
    reviews: 276,
    includes: ["Ryokan Stay", "Shinkansen Pass", "Tea Ceremony", "Sake Tasting", "All Breakfasts"],
    itinerary: [],
    category: "Cultural",
    badge: "New",
    departure: "Every Friday",
  },
  {
    id: "6",
    title: "African Safari Expedition",
    destination: "Kenya & Tanzania",
    image: "https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=800&q=80",
    images: [],
    price: 5499,
    originalPrice: 6999,
    duration: "14 days",
    groupSize: "4-8",
    difficulty: "Moderate",
    rating: 4.9,
    reviews: 143,
    includes: ["Safari Lodge", "All Meals", "Game Drives", "Hot Air Balloon", "Park Fees"],
    itinerary: [],
    category: "Wildlife",
    badge: "Premium",
    departure: "Every Sunday",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Sarah Mitchell",
    avatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&q=80",
    location: "New York, USA",
    rating: 5,
    review: "WanderBase completely transformed how I travel. The Bali trip was beyond magical — every detail was perfect. From the villa to the temple tours, I felt like a VIP the entire time. Will definitely book again!",
    tour: "Bali Spirit Journey",
    date: "2024-03-15",
  },
  {
    id: "2",
    name: "James Thompson",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80",
    location: "London, UK",
    rating: 5,
    review: "The Greek Islands tour was absolutely spectacular. Our guide Nikos was incredibly knowledgeable, and the itinerary was perfectly paced. Santorini at sunset is something I'll never forget. 10/10!",
    tour: "Greek Islands Odyssey",
    date: "2024-02-20",
  },
  {
    id: "3",
    name: "Priya Sharma",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&q=80",
    location: "Mumbai, India",
    rating: 5,
    review: "The Maldives luxury package was worth every penny. The overwater villa, the snorkeling with whale sharks, the private beach dinners — pure paradise. WanderBase knows how to do luxury right!",
    tour: "Maldives Luxury Escape",
    date: "2024-01-08",
  },
  {
    id: "4",
    name: "Carlos Mendez",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&q=80",
    location: "Madrid, Spain",
    rating: 4,
    review: "The Inca Trail was challenging but absolutely worth it. Standing at Machu Picchu after the trek was one of the most emotional moments of my life. The guides were professional and supportive throughout.",
    tour: "Inca Trail Adventure",
    date: "2024-04-02",
  },
  {
    id: "5",
    name: "Emma Wilson",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&q=80",
    location: "Sydney, Australia",
    rating: 5,
    review: "Kenya Safari was the trip of a lifetime. Witnessing the Great Migration was breathtaking. The lodge was stunning, guides were exceptional, and the photography opportunities were incredible!",
    tour: "African Safari Expedition",
    date: "2024-03-28",
  },
  {
    id: "6",
    name: "Yuki Tanaka",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&q=80",
    location: "Tokyo, Japan",
    rating: 5,
    review: "Ironically, WanderBase showed me parts of my own country I had never seen. The cultural immersion tour through Kyoto and Nara was deeply moving. The ryokan experience was unforgettable.",
    tour: "Japan Cultural Immersion",
    date: "2024-02-14",
  },
];

export const galleryImages: GalleryImage[] = [
  { id: "1", src: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80", alt: "Mountain peaks at sunset", location: "Swiss Alps", category: "Mountains" },
  { id: "2", src: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80", alt: "Tropical beach paradise", location: "Maldives", category: "Beach" },
  { id: "3", src: "https://images.unsplash.com/photo-1548013146-72479768bada?w=800&q=80", alt: "Taj Mahal at dawn", location: "Agra, India", category: "Culture" },
  { id: "4", src: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&q=80", alt: "Cinque Terre colorful villages", location: "Italy", category: "Cities" },
  { id: "5", src: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80", alt: "Road through autumn forest", location: "Canada", category: "Nature" },
  { id: "6", src: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=800&q=80", alt: "Snorkeling in coral reef", location: "Great Barrier Reef", category: "Beach" },
  { id: "7", src: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=800&q=80", alt: "Desert sand dunes", location: "Sahara, Morocco", category: "Desert" },
  { id: "8", src: "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800&q=80", alt: "Northern lights over lake", location: "Iceland", category: "Nature" },
  { id: "9", src: "https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80", alt: "Lush tropical waterfall", location: "Bali, Indonesia", category: "Nature" },
];

export const stats: Stat[] = [
  { value: "50K+", label: "Happy Travelers", icon: "users" },
  { value: "120+", label: "Destinations", icon: "globe" },
  { value: "15+", label: "Years Experience", icon: "award" },
  { value: "4.9★", label: "Average Rating", icon: "star" },
];
